spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server_db
    username: postgres
    password: letmein
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

logging:
  level:
    org:
      hibernate:
        sql:
          DEBUG