version: "3.3"
services:
  postgres:
    container_name: server_postgresql_db
    image: postgres
    volumes:
      - postgres_data_servers:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: letmein
    ports:
      - "5432:5432"
volumes:
  postgres_data_servers:
    driver: local